name: Say hello

on:
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      app-version: ${{ steps.package-version.outputs.current-version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: get-npm-version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@v1.3.1
      - name: Fail
        run: exit 1
  deploy_pre:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Success
        run: exit 0
      #- name: Fail
      #  run: exit 1
  deploy_pro:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Success
        run: exit 0
      #- name: Fail
      #  run: exit 1
  notify:
    env:
      VERSION: ${{ needs.build.outputs.app-version }}
    if: ${{ always() }}
    needs: [build, deploy_pre, deploy_pro]
    runs-on: ubuntu-latest
    steps:
      - name: Send message when deploy is success
        if: needs.build.result == 'success' && needs.deploy_pre.result == 'success' && needs.deploy_pro.result == 'success'
        run: echo "Deployed *app* in *Cloud Run*! - Deployed version $VERSION"

      - name: Send message when deploy fails
        if: needs.build.result == 'failure' || needs.deploy_pre.result == 'failure' || needs.deploy_pro.result == 'failure'
        run: echo "Ha fallado el despliegue de *app* en Cloud Run $VERSION"
