name: Say hello

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    outputs:
      app-version: ${{ steps.package-version.outputs.current-version }}
    steps:
      - name: get-npm-version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@v1.3.1
  notify:
    env:
      MASTER_BRANCH: 'refs/heads/main'
      VERSION: ${{ needs.build_and_deploy.outputs.app-version }}
    if: ${{ always() }}
    needs: [build_and_deploy]
    runs-on: ubuntu-latest
    steps:
      - name: Send message when deploy is success
        if: needs.build_and_deploy.result == 'success' && github.ref == env.MASTER_BRANCH
        run: echo "Deployed *bipiapp* in *Cloud Run*! - Deployed version $VERSION"

      - name: Send message when deploy fails
        if: failure() && github.ref == env.MASTER_BRANCH
        run: echo "Ha fallado el despliegue de *bipiapp* en Cloud Run $VERSION"
