name: Version Checker

on:
  workflow_run:
    workflows: ["Say hello"]
    types:
      - completed
  workflow_dispatch:
  
concurrency:
  group: "Say hello-refs/heads/main"
  cancel-in-progress: true

jobs:
  check_production_deployed_version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Get package version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@v1.3.1
        
      - name: Get deployed version
        id: deployed-version
        uses: fjogeleit/http-request-action@v1.14.1
        with:
          url: 'https://portal.bipiapp.com/api/_version'
          method: 'GET'

      - name: Send message when versions differ
        env:
          PACKAGE_VERSION: ${{ steps.package-version.outputs.current-version }}
          DEPLOYED_VERSION: ${{ fromJson(steps.deployed-version.outputs.response).version }}
        if: ${{ env.PACKAGE_VERSION != env.DEPLOYED_VERSION }}
        run: echo "Deployed version $DEPLOYED_VERSION differs from the $PACKAGE_VERSION please check the pinged revision in GCloud"
