name: Version Checker

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  check_production_deployed_version:
    runs-on: ubuntu-latest
    outputs:
      app-version: ${{ steps.package-version.outputs.current-version }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Get package version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@v1.3.1
      
      - name: Get deployed version
        id: deployed-version
        uses: fjogeleit/http-request-action@v1.14.1
        with:
          url: 'https://portal.bipiapp.com/api/_version'
          method: 'GET'

      - name: Send message when versions differ
        run: echo ${{ steps.deployed-version.outputs.response }}
