name: Version Checker

on:
  workflow_call:
    inputs:
      package-version:
        required: true
        type: string
  workflow_dispatch:

jobs:
  check_deployed_version:
    runs-on: ubuntu-latest
    steps:
      - name: Get deployed version
        id: deployed-version
        uses: fjogeleit/http-request-action@v1.14.1
        with:
          url: 'https://portal.bipiapp.com/api/_version'
          method: 'GET'

      - name: Send message when versions differ
        env:
          PACKAGE_VERSION: ${{ inputs.package-version }}
          DEPLOYED_VERSION: ${{ fromJson(steps.deployed-version.outputs.response).version }}
        if: ${{ env.PACKAGE_VERSION != env.DEPLOYED_VERSION }}
        run: echo "Deployed version $DEPLOYED_VERSION differs from the $PACKAGE_VERSION please check the pinged revision in GCloud"
